name: CI

on: [push]

env:
  TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
  TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}

jobs:
  test-ubuntu:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print Swift version
        run: swift --version
      - name: Run tests
        run: swift test --enable-test-discovery
      - name: Build
        run: swift build -c release

  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print Swift version
        run: swift --version
      - name: Run tests
        run: swift test
      - name: Build
        run: swift build -c release
