name: CI

on: [push]

jobs:
  test-ubuntu:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: swift test --enable-test-discovery
      - name: Build
        run: swift build -c release

  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: swift test
      - name: Build
        run: swift build -c release
